preset: psr2

enabled:
    - blank_line_after_opening_tag
    - blank_line_before_return
    - method_separation
    - no_empty_comment
    - no_empty_phpdoc
    - phpdoc_add_missing_param_annotation
    - phpdoc_align
    - phpdoc_annotation_without_dot
    - phpdoc_indent
    - phpdoc_inline_tag
    - phpdoc_no_access
    - phpdoc_no_empty_return
    - phpdoc_no_package
    - phpdoc_order
    - phpdoc_scalar
    - phpdoc_separation
    - phpdoc_single_line_var_spacing
    - phpdoc_summary
    - phpdoc_to_comment
    - phpdoc_trim
    - phpdoc_types
    - phpdoc_var_without_name
    - space_after_semicolon
    - standardize_not_equals

finder:
  name:
    - "*.php"
  not-path:
    - "Configuration"
    - "Documentation"
    - "Resources"
